// Run against a local frontend with Playwright installed or PLAYWRIGHT_MODULE set.
// All API calls are intercepted; this check consumes no provider quota.
const fs=require('fs');
const {chromium}=require(process.env.PLAYWRIGHT_MODULE || 'playwright');
const base=process.env.BUYWISE_UI_URL || 'http://localhost:3107';
const origin=new URL(base).origin;
const check=(ok,msg)=>{if(!ok)throw new Error(msg)};
(async()=>{
 const browser=await chromium.launch({headless:true,...(process.env.PLAYWRIGHT_CHROMIUM_PATH ? {executablePath:process.env.PLAYWRIGHT_CHROMIUM_PATH} : {})});
 const context=await browser.newContext({viewport:{width:1440,height:1000},reducedMotion:'reduce'});
 const p=await context.newPage(); const errors=[];p.on('pageerror',e=>errors.push(e.message));
 let apiCalls=0;const reqs=[{id:'r1',key:'budget',operator:'<=',value:'300000 PKR',priority:'must',source:'user'},{id:'r2',key:'ram',operator:'>=',value:'16 GB',priority:'must',source:'user'}];
 await p.route('**/api/**',async route=>{apiCalls++;const url=route.request().url();const headers={'access-control-allow-origin':origin,'access-control-allow-headers':'content-type','access-control-allow-methods':'GET,POST,OPTIONS'};if(route.request().method()==='OPTIONS')return route.fulfill({status:204,headers});
 if(url.endsWith('/analyze-requirements'))return route.fulfill({status:200,headers,contentType:'application/json',body:JSON.stringify({request_id:'design-check',category:'laptop',requirements:reqs,missing_info:[],data_mode:'fixture',notices:['UI verification fixture: no Gemini calls.']})});
 if(url.includes('/comparison/empty-design'))return route.fulfill({status:200,headers,contentType:'application/json',body:JSON.stringify({id:'empty-design',request_id:'design-check',created_at:new Date().toISOString(),products:[],requirements:reqs,requirement_matches:{},requirement_analysis:[],tradeoffs:[],data_mode:'fixture',notices:['No exact match found.']})});
 return route.fulfill({status:503,headers,contentType:'application/json',body:JSON.stringify({error:{code:'UNAVAILABLE',message:'Test backend unavailable. Please retry.'}})});
 });
 await p.goto(base);await p.getByLabel('Shopping request',{exact:true}).waitFor();check(await p.getByRole('button',{name:'Start research',exact:true}).isDisabled(),'Empty prompt should not submit');
 await p.getByRole('button',{name:'Gaming without overspending',exact:true}).click();check((await p.getByLabel('Shopping request',{exact:true}).inputValue()).includes('8 GB VRAM'),'Example failed');await p.getByRole('button',{name:'Start research',exact:true}).click();await p.getByRole('heading',{name:'A good decision starts here.'}).waitFor();await p.getByLabel('Requirement 1 value').waitFor();await p.getByLabel('Requirement 2 value').fill('32 GB');await p.screenshot({path:'/tmp/buywise-requirements-redesign.png',fullPage:true});await p.reload();await p.getByLabel('Requirement 2 value').waitFor();check(await p.getByLabel('Requirement 2 value').inputValue()==='32 GB','Edits lost on reload');
 await p.getByRole('button',{name:'Remove requirement 1',exact:true}).click();await p.getByRole('button',{name:'Keep requirement',exact:true}).click();check(await p.getByLabel('Requirement 1 value').count()===1,'Must-have confirmation failed');
 await p.goto(base+'/results/demo');await p.getByRole('heading',{name:'Your research, in context.',exact:true}).waitFor();check(await p.locator('.product-card').count()===3,'Demo cards missing');await p.locator('.source-notices summary').click();check(await p.getByText('Static illustration only:',{exact:false}).isVisible(),'Source notices hidden after expand');await p.locator('.source-notices summary').click();
 await p.locator('.comparison-table .citation-button').first().click();await p.getByRole('dialog').waitFor();await p.screenshot({path:'/tmp/buywise-evidence-redesign.png'});await p.keyboard.press('Escape');check(await p.getByRole('dialog').count()===0,'Escape failed');
 await p.getByRole('link',{name:'Explore evidence',exact:true}).first().click();await p.getByRole('tab',{name:'Warranty',exact:true}).click();await p.getByRole('tabpanel').waitFor();await p.getByRole('tab',{name:'Specifications',exact:true}).click();await p.getByRole('tab',{name:'Specifications',exact:true}).focus();await p.keyboard.press('ArrowRight');check(await p.getByRole('tab',{name:'Evidence',exact:true}).getAttribute('aria-selected')==='true','Keyboard tab selection failed');await p.keyboard.press('Home');await p.screenshot({path:'/tmp/buywise-product-redesign.png',fullPage:true});
 await p.getByRole('button',{name:'Toggle theme',exact:true}).click();check(await p.evaluate(()=>getComputedStyle(document.documentElement).colorScheme)==='dark','Dark theme failed');await p.screenshot({path:'/tmp/buywise-product-dark.png',fullPage:true});await p.reload();await p.getByRole('tab',{name:'Specifications',exact:true}).waitFor();check(await p.evaluate(()=>getComputedStyle(document.documentElement).colorScheme)==='dark','Theme lost on reload');await p.getByRole('button',{name:'Toggle theme',exact:true}).click();
 await p.goto(base+'/results/empty-design');await p.getByRole('heading',{name:'No supported match this time.',exact:true}).waitFor();check(await p.locator('.comparison-table').count()===0,'Empty table should not render');await p.screenshot({path:'/tmp/buywise-empty-redesign.png',fullPage:true});
 await p.goto(base+'/results/outage-design');await p.getByRole('button',{name:'Retry',exact:true}).waitFor();
 await p.setViewportSize({width:390,height:844});await p.goto(base);await p.getByLabel('Shopping request',{exact:true}).waitFor();check(await p.evaluate(()=>document.documentElement.scrollWidth<=window.innerWidth),'Home mobile overflow');await p.screenshot({path:'/tmp/buywise-home-mobile.png',fullPage:true});await p.getByRole('button',{name:'Open navigation',exact:true}).click();check(await p.getByRole('navigation',{name:'Mobile navigation'}).isVisible(),'Mobile nav failed');await p.getByRole('link',{name:'View demo results',exact:true}).click();await p.getByRole('heading',{name:'Your research, in context.',exact:true}).waitFor();check(await p.evaluate(()=>document.documentElement.scrollWidth<=window.innerWidth),'Results mobile overflow');await p.screenshot({path:'/tmp/buywise-results-mobile.png',fullPage:true});
 await p.getByRole('button',{name:'Toggle theme',exact:true}).click();await p.screenshot({path:'/tmp/buywise-results-mobile-dark.png',fullPage:true});
 check(errors.length===0,'Browser errors: '+errors.join('; '));
 const report={status:'passed',real_provider_calls:0,intercepted_fixture_requests:apiCalls,browser_errors:errors,checks:['request examples','submission','editable requirements','reload persistence','must-have removal confirmation','demo results','notice disclosure','evidence drawer and Escape','product tabs and keyboard arrows','dark mode and persistence','empty results','backend failure retry','mobile navigation','390px overflow']};fs.writeFileSync('Doc/UI-REDESIGN-CHECKS.json',JSON.stringify(report,null,2));console.log(JSON.stringify(report));await browser.close();
})().catch(e=>{console.error(e);process.exit(1)});
