async page => {
  const errors=[],calls=[]
  const check=(ok,message)=>{if(!ok)throw new Error(message)}
  page.on('pageerror',e=>errors.push(e.message))
  page.on('request',r=>{if(r.url().includes('/api/'))calls.push({url:r.url(),body:r.postData()})})
  await page.goto('http://localhost:3107/')
  await page.getByLabel('Shopping request').fill('I need a laptop with 16 GB RAM, budget 600 USD')
  await page.getByRole('button',{name:'Start research',exact:true}).click()
  await page.getByLabel('Requirement 2 value').waitFor()
  check(await page.getByLabel('Requirement 1 value').inputValue()==='600 USD','Incorrect extracted budget')
  await page.getByLabel('Requirement 1 value').fill('1200 USD')
  await page.getByLabel('Requirement 2 value').fill('32 GB')
  await page.getByLabel('Requirement 2 priority').selectOption('high')
  await page.getByLabel('Remove requirement 1').click()
  await page.getByRole('button',{name:'Keep requirement',exact:true}).click()
  await page.getByRole('button',{name:'Add requirement',exact:true}).click()
  await page.getByLabel('Requirement 3 key').fill('os_compatibility')
  await page.getByLabel('Requirement 3 value').fill('Linux')
  await page.getByLabel('Clarification answer').fill('I also need 1 TB SSD')
  await page.getByRole('button',{name:'Analyze clarification',exact:true}).click()
  await page.getByLabel('Requirement 4 value').waitFor()
  check(await page.getByLabel('Requirement 1 value').inputValue()==='1200 USD','Clarification lost edits')
  check(await page.getByLabel('Requirement 4 value').inputValue()==='1 TB','Missing clarification criterion')
  await page.reload()
  await page.getByLabel('Requirement 4 value').waitFor()
  await page.getByRole('button',{name:'Confirm and research',exact:true}).click()
  await page.getByRole('heading',{name:'Your research, in context.',exact:true}).waitFor({timeout:30000})
  const original=page.url()
  check(await page.locator('article').count()===5,'Wrong backend candidates')
  check(calls.some(c=>c.url.includes('/api/stream/')),'SSE was not opened')
  const submitted=JSON.parse(calls.filter(c=>c.url.endsWith('/api/research-products')).at(-1).body)
  check(submitted.requirements.some(r=>r.key==='ram'&&r.value==='32 GB'&&r.priority==='high'&&r.confirmed),'Edits not submitted')
  await page.reload()
  await page.getByRole('heading',{name:'Your research, in context.',exact:true}).waitFor()
  check(page.url()===original,'Result refresh identity changed')
  await page.getByRole('link',{name:'Explore evidence',exact:true}).first().click()
  await page.getByRole('tab',{name:'Warranty',exact:true}).click()
  check((await page.getByRole('tabpanel').innerText()).includes('12 months'),'Wrong warranty')
  await page.getByRole('tab',{name:'Evidence',exact:true}).click()
  await page.getByRole('tabpanel').getByRole('button').first().click()
  await page.getByRole('dialog').waitFor()
  check((await page.getByRole('dialog').innerText()).includes('fixture'),'Missing provenance')
  await page.keyboard.press('Escape')
  await page.getByRole('dialog').waitFor({state:'hidden'})
  await page.reload()
  await page.getByRole('tab',{name:'Specifications',exact:true}).waitFor()
  await page.getByRole('link',{name:'Back to results',exact:false}).click()
  await page.getByLabel('Follow-up question').fill('What RAM do these have?')
  await page.getByRole('button',{name:'Ask question',exact:true}).click()
  await page.getByText('Synthetic demo/fixture data.',{exact:false}).waitFor()
  check(JSON.parse(calls.filter(c=>c.url.endsWith('/api/follow-up')).at(-1).body).comparison_id===original.split('/').pop(),'Wrong follow-up comparison ID')
  await page.getByLabel('Follow-up question').fill('What if my budget is $2000?')
  await page.getByRole('button',{name:'Ask question',exact:true}).click()
  await page.getByRole('button',{name:'Confirm suggested changes and regenerate',exact:true}).click()
  await page.waitForURL(url=>url.pathname.startsWith('/results/')&&url.href!==original,{timeout:30000})
  await page.getByLabel('Budget ceiling').waitFor()
  check(await page.getByLabel('Budget ceiling').inputValue()==='2000','Budget patch missing')
  const before=page.url()
  await page.getByLabel('Budget ceiling').fill('1800')
  await page.getByRole('button',{name:'Apply budget and regenerate',exact:true}).click()
  await page.waitForURL(url=>url.pathname.startsWith('/results/')&&url.href!==before,{timeout:30000})
  await page.getByLabel('Budget ceiling').waitFor()
  check(await page.getByLabel('Budget ceiling').inputValue()==='1800','Budget control did not regenerate')
  await page.locator('article input[type=checkbox]').nth(0).check()
  await page.locator('article input[type=checkbox]').nth(1).check()
  await page.getByRole('button',{name:'Compare selected products',exact:true}).click()
  await page.waitForFunction(()=>document.querySelectorAll('article').length===2)
  await page.goBack();await page.waitForFunction(()=>document.querySelectorAll('article').length===5)
  await page.goForward();await page.waitForFunction(()=>document.querySelectorAll('article').length===2)
  await page.setViewportSize({width:390,height:844})
  check(await page.evaluate(()=>document.documentElement.scrollWidth<=window.innerWidth),'Mobile overflow')
  await page.goto('http://localhost:3107/results/missing-p4-test')
  await page.getByRole('button',{name:'Retry',exact:true}).waitFor()
  await page.goto('http://localhost:3107/')
  await page.getByLabel('Shopping request').fill('I want a monitor under $500')
  await page.getByRole('button',{name:'Start research',exact:true}).click()
  await page.getByText('This request is outside the supported category.',{exact:false}).waitFor()
  check(await page.getByRole('button',{name:'Confirm and research',exact:true}).isDisabled(),'Unsupported research enabled')
  check(errors.length===0,'Runtime errors: '+errors.join('; '))
  console.log('PASS: full P4 fixture workflow, refresh, history, mobile, missing-result and unsupported-category; '+calls.length+' requests; zero page errors')
}
