async page => {
  const errors = [], calls = []
  const check = (ok, message) => { if (!ok) throw new Error(message) }
  page.on('pageerror', e => errors.push(e.message))
  page.on('request', r => { if (r.url().endsWith('/api/research-products')) calls.push(JSON.parse(r.postData())) })
  const id = '05935d29-ec2e-4f34-bc79-7be0b475109e'
  await page.setViewportSize({width:1280,height:900})
  await page.goto(`http://localhost:3107/results/${id}`)
  await page.getByRole('heading',{name:'Your research, in context.',exact:true}).waitFor()
  check(await page.locator('article').count() === 3, 'Missing regional candidates')
  check(await page.getByLabel('Budget ceiling').inputValue() === '300000', 'PKR ceiling did not load')
  check((await page.locator('main').innerText()).includes('three approved Paklap SKUs'), 'Coverage notice missing')
  check(await page.getByText('Stale price · current budget fit uncertain',{exact:true}).count() === 3, 'Undated prices look fresh')
  await page.getByRole('link',{name:'Explore evidence',exact:true}).first().click()
  await page.getByRole('tab',{name:'Warranty',exact:true}).click()
  const policy = await page.getByRole('tabpanel').innerText()
  check(policy.includes('unknown') || policy.includes('Unknown'), 'Default HP duration invented')
  await page.getByRole('tab',{name:'Return policy',exact:true}).click()
  const returns = await page.getByRole('tabpanel').innerText()
  check(returns.includes('Return window unknown') && returns.includes('Conditional'), 'Replacement conditions missing')
  await page.getByRole('tab',{name:'Evidence',exact:true}).click()
  await page.getByRole('tabpanel').getByRole('button').first().click()
  await page.getByRole('dialog').waitFor()
  const drawer = await page.getByRole('dialog').innerText()
  check(drawer.includes('curated') && drawer.includes('paklap.pk'), 'Source provenance missing')
  check(await page.getByRole('link',{name:'Open source',exact:false}).count() === 1, 'Attributed retailer source cannot be opened')
  await page.keyboard.press('Escape')
  await page.getByRole('link',{name:'Back to results',exact:false}).click()
  await page.getByLabel('Budget ceiling').fill('350000')
  await page.getByRole('button',{name:'Apply budget and regenerate',exact:true}).click()
  await page.waitForURL(url => url.pathname.startsWith('/results/') && url.pathname !== `/results/${id}`, {timeout:60000})
  await page.getByLabel('Budget ceiling').waitFor()
  check(await page.getByLabel('Budget ceiling').inputValue() === '350000', 'Regenerated PKR ceiling missing')
  check(calls.at(-1).requirements.some(r => r.key === 'budget' && r.value === '350000 PKR'), 'Regeneration silently changed currency')
  const regenerated = page.url()
  await page.reload()
  await page.getByRole('heading',{name:'Your research, in context.',exact:true}).waitFor()
  check(page.url() === regenerated && await page.locator('article').count() === 3, 'Durable result reload failed')
  await page.getByLabel('Follow-up question').fill('What if my budget is PKR 400000?')
  await page.getByRole('button',{name:'Ask question',exact:true}).click()
  await page.getByText('Confirm the suggested PKR ceiling',{exact:false}).waitFor()
  await page.getByRole('button',{name:'Confirm suggested changes and regenerate',exact:true}).click()
  await page.waitForURL(url => url.pathname.startsWith('/results/') && url.href !== regenerated,{timeout:60000})
  await page.getByLabel('Budget ceiling').waitFor()
  check(await page.getByLabel('Budget ceiling').inputValue() === '400000', 'Follow-up patch changed currency')
  await page.locator('article input[type=checkbox]').nth(0).check()
  await page.locator('article input[type=checkbox]').nth(1).check()
  await page.getByRole('button',{name:'Compare selected products',exact:true}).click()
  await page.waitForFunction(() => document.querySelectorAll('article').length === 2)
  await page.setViewportSize({width:390,height:844})
  check(await page.evaluate(() => document.documentElement.scrollWidth <= window.innerWidth), 'PKR mobile overflow')
  check(errors.length === 0, 'Runtime errors: ' + errors.join('; '))
  return 'PASS: live PKR source detail/links, unknown policies/stale prices, durable refresh, PKR budget/follow-up regeneration, selected comparison, mobile; zero page errors'
}
